# Generated by Django 3.2.9 on 2022-04-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetailsmodel',
            name='licences_no',
        ),
    ]
